parserOptions:
    ecmaVersion: 8
    sourceType: module

env:
    es6: true
    browser: true
    node: true

extends:
    "eslint:recommended"

rules:
    no-cond-assign: 0
    no-mixed-spaces-and-tabs: 0
    valid-jsdoc: 1
